Pool Create UX Improvements (Balancer)
berachain/monobera pull request #185
Opened 2024-11-11 18:06 UTC by PaulMcInnis

This adds:

- the weights/locking UX
- amplification parameter for stable pool creation
- improved look and feel (closer to design)
- tooltips are beside labels in InputWithLabel
- correct ownership UX
 
 TODO
- [x] debounce so the weights input is usable (very hard to use with on-change)
- [x] error message if the weights dont add to 1 (let user break the total by keeping what they type and checking)
- [x] properly display the ownership options via a multi-selector (and default to governance address)
- [x] dump fixed fee display from the type cards
- [ ] show clearly somewhere that rate provider is 0x0 for stable pools
- [x] warning for if liquidity doesnt align with weight inputs
    - [ ] make it dynamically displayed and only in the correct situation (honey equiv may not exist)
- [x] show an error if a user creates a 0 weight
- [x] lock weights on user edit
- [x] instead of stacking approval buttons as disabled, just show them one at a time
- [x] filter out BGT
- [x] handle properly wallet !connected state (don't show approvals)
- [x] decimals behave weirdly (33.33 case, try and edit last decimal)
- [x] duplication detection should not block you from pool creation (warning)
- [ ] move `0xba1ba1ba1ba1ba1ba1ba1ba1ba1ba1ba1ba1ba1b` into config
- [ ] double check that with 8 token weighted naming we don't run out of space
- [x] dont disallow liquidity token value entry
- [ ] allow changing pools without losing tokens
- [ ] size of input for set swap fee
- [ ] use the input background variant for all inputs (black) 
- [ ] try and match the figma spacings exactly
- [ ] Fees modified by --> fee ownership
- [ ] break down the component
- [x] filter out BERA from token selection (does creation helper wrap?)
- [ ] allow BERA as a liquidity token selection and handle BERA->WBERA wrap
- [ ] disable create pool until liquidity has been entered (disallow 0 case)

Future work:
- [ ] expose rate provider input (metastable)
- [ ] break down this huge component

2024-11-12 17:52 UTC, bearpong requested changes
Good job on this, it's working generally fine except some bugs. 

I've also added some comments on things that might be improved since we have some more bandwidth now! 🥳

2024-11-12 17:52 UTC, bearpong commented on apps/hub/src/b-sdk/usePoolWeights.tsx
> +  );
imo, i think we should set refactor to smth like this:
```
const [weights, setWeights] = useState<{
value: bigint;
formattedValue: string; // just for readability when rendering the component
isLocked: boolean;
isActive: boolean; // true if it's being edited by the user and value shouldn't change 
}[]>([])
```

this probably means that on the component you have just a state `input`, which replaces formattedValue on the input where `isActive` is `true`.

in this way you avoid updating the values that are either locked or being edited

2024-11-12 17:52 UTC, bearpong commented on apps/hub/src/b-sdk/usePoolWeights.tsx
> +    });
this is weird in terms of UX, it should behave as if it's locked, but it shouldn't get locked permanently. see proposed change above for fixing this

2024-11-12 17:52 UTC, bearpong commented on apps/hub/src/app/pools/components/pool-type-selector.tsx
> +          <span className="mt-[-4px] text-sm text-muted-foreground">
please use `-mt-1`

2024-11-12 17:52 UTC, bearpong commented on apps/hub/src/app/pools/components/ownership-input.tsx
> +          <span className="mt-[-4px] text-sm text-muted-foreground">
please use `-mt-1` and in other occurencies as well

2024-11-12 17:52 UTC, bearpong commented on apps/hub/src/app/pools/components/ownership-input.tsx
> +          onClick={() => onChangeOwnershipType("governance")}
Can you store the ownership types in an enum?

2024-11-12 17:52 UTC, bearpong commented on apps/hub/src/app/pools/components/ownership-input.tsx
> +      </div>
Please let's show the input only when the the ownership type is set to custom address.

2024-11-12 17:53 UTC, bearpong commented on apps/hub/src/hooks/useCreatePool.ts
>    const {
sorry this was referred to the `useCreatePool__deduped_pool` hook

2024-11-12 20:03 UTC, PaulMcInnis commented on apps/hub/src/hooks/useCreatePool.ts
> +  const exemptFromYieldProtocolFeeFlag = false; // FIXME: should this ever be true?
Ah thanks for highlighting this, I needed to revisit this.

For weighted pools, **we can indeed pass rateProviders,** and furthermore [if they are all 0x0](https://github.com/balancer/balancer-v2-monorepo/blob/36d282374b457dddea828be7884ee0d185db06ba/pkg/pool-weighted/contracts/WeightedPoolProtocolFees.sol#L74) we are exempt from protocol fees on the yield automatically. i.e. if the change in value of tokens appreciates according to rate providers we don't charge a fee on this, and the exemption is true. 


For stable pools, drilling into the PoolCreationHelper & Stable pool init, it seems the core logic that accepts the flag I am passing is [here](https://github.com/balancer/balancer-v2-monorepo/blob/36d282374b457dddea828be7884ee0d185db06ba/pkg/pool-stable/contracts/ComposableStablePoolStorage.sol#L146), and it clearly states `The exemptFromYieldFlag should never be set on a token without a rate provider.`

So essentially I see two action items here:
1. we should plan to pass rate providers in weighted pools FE, and until we do we should explicitly pass `true`.
2. we should continue to pass `false` for stable pools with 0x0 rate providers, and when we introduce metastable pool creation (with rate providers), we can optionally pass `true` 


I will confirm this with Jason tomorrow though as well.

2024-11-13 00:50 UTC, PaulMcInnis commented on pnpm-lock.yaml
I guess I might have made a mistake committing this, basically I just want the berancer-sdk in the beraJs package.

2024-11-13 11:38 UTC, bearpong commented on pnpm-lock.yaml
wdym?

2024-11-13 15:17 UTC, PaulMcInnis commented on apps/hub/src/b-sdk/usePoolWeights.tsx
> +    });
NOTE: future work here around being able to modify a value and not have that 'active' value normalized, so that then locking and unlocking is only done by clicking on the lock itself.

2024-11-13 16:12 UTC, PaulMcInnis commented on apps/hub/src/hooks/useCreatePool.ts
> +  const exemptFromYieldProtocolFeeFlag = false; // FIXME: should this ever be true?
OK seems that its OK not to be passing this for 1., and for 2. we can revisit as a part of metastable pools w/ rate providers, i'l made it a TODO.

2024-11-13 16:13 UTC, PaulMcInnis commented on pnpm-lock.yaml
merge conflict hell now haha but ill resolve this.

2024-11-13 17:06 UTC, bearpong approved these changes
LGTM

2024-11-13 17:06 UTC, merged