Feature/balancer/pool create wrapping
berachain/monobera pull request #209
Opened 2024-11-20 15:31 UTC by PaulMcInnis

- Wrap BERA -> WBERA as a part of pool creation
    - generated pool namings still use WBERA
    - pricings still use WBERA
    - joinPool args & value of create pool tx handle BERA case (payable tx)
    - de-dupe pool checks still use WBERA
    - selection of BERA and WBERA is mutually exclusive

NOTES:
- I am noticing that the dedupe weighted pools query seems not to be working right now
- I also updated the ABI to v6 as is currently deployed for stable pools in the event decoding, this ABI probably belongs in berancer repo though. 
- you can select between BERA and WBERA in the add initial liquidity section like when you are adding liquidity to an existing pool

2024-11-20 22:33 UTC, PaulMcInnis commented on apps/hub/src/app/pools/components/create-pool-input.tsx
> +  // Do not allow the user to select BERA and WBERA as a token pair. (NOTE: BERA is wrapped during create)
This works but there is a UX issue where you cannot change BERA to WBERA in the token selection as the other option is filtered out to prevent you creating a BERA:WBERA pool.

2024-11-20 22:33 UTC, PaulMcInnis commented on apps/hub/src/app/pools/create/CreatePageContent.tsx
> +                : balancerComposableStablePoolFactoryV6),
We have deployed V6 not V5, so I've updated this

2024-11-20 22:34 UTC, PaulMcInnis commented on packages/berajs/src/utils/tokenWrapping.ts
> +// import { wBeraToken } from "@bera/wagmi";
is there a better place for these utilities? I need them both in beraJS and in hub.

2024-11-22 12:39 UTC, bearpong commented on apps/hub/src/app/pools/components/create-pool-input.tsx
> +  // Do not allow the user to select BERA and WBERA as a token pair. (NOTE: BERA is wrapped during create)
regarding this, i think that in "select tokens" BERA must _not_ be selectable because the pool is actually made of WBERAs.

However the user should be able to choose native beras in the Set Initial Liquidity widget. 

<img width="701" alt="Screenshot 2024-11-22 at 13 35 55" src="https://github.com/user-attachments/assets/7f402381-176a-4aaa-9d00-1756e6c7d945">

Balancer did the same in the old FE. On our dapp we do this already in the add liquidty page.

<img width="474" alt="image" src="https://github.com/user-attachments/assets/04839133-54e7-4f75-8435-73a63cc94cfe">
<img width="539" alt="Screenshot 2024-11-22 at 13 39 06" src="https://github.com/user-attachments/assets/747feb7c-5bfe-4c65-b1d5-f7ac2c4dc46d">

2024-11-22 12:42 UTC, bearpong requested changes
Hey @PaulMcInnis, please look at the comments to see required changes.

Thank you, you're doing a great job!

2024-11-22 19:48 UTC, PaulMcInnis commented on apps/hub/src/app/pools/components/create-pool-input.tsx
> +  // Do not allow the user to select BERA and WBERA as a token pair. (NOTE: BERA is wrapped during create)
sweet ok I've added this feature

2024-11-22 21:56 UTC, PaulMcInnis commented on apps/hub/src/app/pools/create/CreatePageContent.tsx
>                  ? weightedPoolFactoryV4Abi_V2
ah note to myself here, should also update this one to v5

2024-11-25 16:42 UTC, bearpong approved these changes

2024-11-25 16:42 UTC, merged