User-facing Balancer-specific error codes
berachain/monobera pull request #220
Opened 2024-11-25 20:27 UTC by PaulMcInnis

feat(bex): process balancer-specific errors when thrown in a revert/simulation and caught in `useBeraContractWrite`

![Swap fee percentage is below the minimum allowed](https://github.com/user-attachments/assets/29cf4cff-1d62-4b2f-8e6e-4e9e5edde3c6)
![HONEY  STGUSDC](https://github.com/user-attachments/assets/d46caf4c-31aa-4ffb-b28d-927a9db444e8)
![The amplification parameter is below the minimum allowed](https://github.com/user-attachments/assets/545fe461-8fd8-4bd1-8615-acd3056f181f)

2024-11-25 20:58 UTC, PaulMcInnis commented on packages/berajs/src/utils/errorMessages.ts
> +      errorMSG: "Addition overflow occurred during calculation.",
open to including the BAL# in the message

2024-11-26 11:19 UTC, bearpong requested changes
Nice use of the errorMessages.ts though I think we should not fallback to a default message if the BAL error is not mapped in the array. I would match the BAL#000 error, and if present map it and always show it in the UI. It'd be easier to debug user issues when reported.

After that please do the same on useAddLiquidity as you suggested

2024-11-26 11:19 UTC, bearpong commented on packages/berajs/src/utils/errorMessages.ts
> +      errorMSG: "Addition overflow occurred during calculation.",
yes please

2024-11-26 15:01 UTC, PaulMcInnis commented
OK added this to useAddLiquidity 👍

2024-11-28 19:50 UTC, PaulMcInnis commented
OK after reviewing https://docs.balancer.fi/reference/contracts/error-codes.html I've pulled in a bunch more codes

2024-12-02 18:08 UTC, PaulMcInnis commented
OK I will fix handling for swap paths shortly

2024-12-03 15:24 UTC, PaulMcInnis commented
Added coverage for this:
<img width="504" alt="image" src="https://github.com/user-attachments/assets/488af402-0ab4-4395-b72f-e128274a2809">

here's an existing error as well
<img width="272" alt="image" src="https://github.com/user-attachments/assets/6105b86b-d89a-442b-a3f7-148e238024bb">

2024-12-05 15:04 UTC, PaulMcInnis commented
OK I will add handling for tx timeout due to swap deadline next

2024-12-05 15:47 UTC, PaulMcInnis commented
<img width="543" alt="image" src="https://github.com/user-attachments/assets/5c04ff79-33d9-4d91-aac4-076696d0eed1">
already covered

2024-12-05 15:49 UTC, bearpong approved these changes

2024-12-05 15:49 UTC, merged