Posthog Analytics
berachain/monobera pull request #226
Opened 2024-11-28 19:16 UTC by PaulMcInnis

This migrates from MixPanel analytics over to PostHog, and changes some events to include more data per the [spec](https://www.notion.so/berachain/PostHog-docs-1276120abced805aa7cfe8f0753a13cd).

2024-12-03 19:57 UTC, PaulMcInnis commented
OK, this is effectively `blocked` until we decide if we want to change the events to match the new incoming ones

2024-12-04 17:48 UTC, PaulMcInnis commented
OK this first PR will focus on a subset of events 👍

2024-12-04 19:20 UTC, PaulMcInnis commented on apps/hub/src/components/swap-card.tsx
> +        track(`swap_${selectedFrom.symbol}`, {
This should instead be swap_token, and we will keep the payload

2024-12-05 00:34 UTC, PaulMcInnis commented
This adds support for the following events:

- Swap
- Redeem (swap page)
- add/withdraw from Pool
- Stake/Unstake from Vault section (worded as deposit/withdraw currently)

2024-12-05 21:17 UTC, Bearlinguer commented
Cannot see Deposit event, only the clicks around that. The flow is right but don't have "deposit" as a event

2024-12-05 22:07 UTC, PaulMcInnis commented on packages/shared-ui/src/utils/analytics.ts
> +  console.log(
dump this

2024-12-09 16:12 UTC, PaulMcInnis commented on apps/hub/src/app/pools/[poolId]/withdraw/WithdrawPageContent.tsx
> +      <Card className="mx-6 flex w-full flex-col items-center bg-background p-4 sm:mx-0 sm:w-[480px]">
alot of these changes are formatting which really ought to be applied project wide.

2024-12-09 16:13 UTC, PaulMcInnis reviewed
👀

2024-12-10 16:05 UTC, bearpong requested changes
gmgm, can we remove mixpanel in this PR?

2024-12-10 16:52 UTC, PaulMcInnis commented on pnpm-lock.yaml
> +  react: <19
we should upgrade to version 19 ([task](https://berachain-fe.atlassian.net/browse/BFE-404), [guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide))

2024-12-10 16:52 UTC, PaulMcInnis reviewed
👀

2024-12-11 23:28 UTC, PaulMcInnis commented
phew! OK, sorted the issue with static build, it seems that we needed to be using node 20 in that GH action. 

RE the node 19/18 debacle I've cut a separate PR to address that #255

2024-12-12 17:17 UTC, bearpong approved these changes

2024-12-12 17:38 UTC, merged