Reset pool create page state after success & preview is closed.
berachain/monobera pull request #227
Opened 2024-11-28 21:57 UTC by PaulMcInnis

Reset the pool creation page state so you can create another pool without refreshing the page provided that the tx was a success

2024-12-02 19:36 UTC, bearpong requested changes
If you try and create a new pool right after you created one, the input are reset however once you click on the preview button, you have the success modal instead of the preview modal.

Please fix this too. Beside that, lgtm

2024-12-02 22:57 UTC, PaulMcInnis commented on apps/hub/src/app/pools/create/CreatePageContent.tsx
> +const DEFAULT_OWNERSHIP_TYPE = OwnershipType.Governance;
change this to Fixed instead

2024-12-03 17:41 UTC, PaulMcInnis commented on apps/hub/src/app/pools/create/CreatePageContent.tsx
> +const DEFAULT_OWNERSHIP_TYPE = OwnershipType.Governance;
actually I will do this here, since it's now a Default

2024-12-05 15:50 UTC, bearpong approved these changes

2024-12-05 15:53 UTC, merged