Set a transaction deadline for swaps
berachain/monobera pull request #239
Opened 2024-12-04 23:15 UTC by PaulMcInnis

Now the tx deadline is respected for swaps per the settings 
<img width="380" alt="image" src="https://github.com/user-attachments/assets/cb182c02-3dc7-4602-8113-40fa9ec26a1f">

NOTE: you can set this deadline very very small to test this, I think really the input should be limited in terms of how small a number you can type, but that is a separate thing.

2024-12-04 23:25 UTC, Bearlinguer commented
Is not better to set "seconds" as default and not "minutes" on the custom deadline? 
I tried a swap with 1e-36 and still working

2024-12-05 00:27 UTC, Bearlinguer commented
@bearpong  have a check

2024-12-05 00:42 UTC, bearpong requested changes
We need to set it to seconds and check if the value is passed properly (n seconds)

2024-12-05 00:58 UTC, PaulMcInnis commented
updated, if you set deadline to around 7 seconds or less it reverts, 30 seconds is the default and that is quite reasonable (vs 30 minutes!)

<img width="421" alt="image" src="https://github.com/user-attachments/assets/02bf5737-1504-4032-a5ad-c583eaf837c0">

2024-12-05 01:40 UTC, PaulMcInnis commented
... ok and now the deadline is propery set to 'infinity' (max safe uint256)

2024-12-05 01:59 UTC, bearpong approved these changes
LGTM beside some tiny details. Do you think there's a way to have a decent error message when it fails due to tx deadline? Bc I think a lot of users might have the error if they wait too long before signing the tx on MM. I don't want them to report us bugs while this is an actual feature

2024-12-05 01:59 UTC, bearpong commented on packages/shared-ui/src/hooks/useDeadline.ts
> +      return 100000; // seconds
This is not used but let's set it to MAX_UINT256 or to null or some other value

2024-12-05 14:46 UTC, PaulMcInnis commented
> LGTM beside some tiny details. Do you think there's a way to have a decent error message when it fails due to tx deadline? Bc I think a lot of users might have the error if they wait too long before signing the tx on MM. I don't want them to report us bugs while this is an actual feature

yes, but I think we need to get #220 in first

2024-12-05 15:00 UTC, merged