chore(bex): Create pool polish
berachain/monobera pull request #246
Opened 2024-12-09 17:42 UTC by thevolcanomanishere

2024-12-13 20:47 UTC, PaulMcInnis commented
OK going to rename Weighted -> "Standard"

2024-12-16 10:34 UTC, bearpong requested changes
Please review the styling with Bobby. From now on everything must be pixel perfect compared to the figma, I see wrong spacing all around the UI. 

feel free to reach out if you wanna see what's wrong

2024-12-16 18:17 UTC, PaulMcInnis commented
OK marking this as draft since there's some lift needed to get this to parity with figma and thats now top priority.

2024-12-17 22:04 UTC, PaulMcInnis commented
OK significantly updated the error handling, and responded to PR feedback, thanks @Bearlinguer 🙏

2024-12-18 19:50 UTC, PaulMcInnis commented
OK I've just pushed up changes to allow creating a pool with rate providers once again. I think we should refine the tooltip text a bit, and there is some consideration around the validity of a 0x0 address.

2024-12-19 04:42 UTC, PaulMcInnis commented on apps/hub/src/app/pools/create/CreatePageContent.tsx
This is getting large again, I think it not now, in the future, we need to break out the stepwise component and validation stuff.

2024-12-19 04:42 UTC, PaulMcInnis commented on packages/berajs/src/hooks/modules/dex/useCreatePool.ts
>  ) => {
Bit of an antipattern here with the zipping and unzipping of stuff like weights and so on. 

I think what would be better would be to use maps/records for these related things vs relying on the index.

2024-12-20 00:17 UTC, PaulMcInnis commented
and now we have an updated warning system which uses BEX API pricings instead of subgraph ones to warn against creating a stable (non-rate-provided-pool) with tokens that are not pegged to the same USD value (at least the price we have currently). 
![image](https://github.com/user-attachments/assets/09da047a-1742-4890-8481-f226e340dfce)

That BEX API pricing also drives our liquidity mismatch warning which handles bad inputs for weighted and stable as well. And the stable mismatch one is clickable (and takes you back to to pool type selection).

We do still however use subgraph pricings for any values in token selection, or when dispalying USD values of tokens in pool create.

2024-12-20 00:18 UTC, PaulMcInnis commented on packages/berajs/src/hooks/tokens/useTokenCurrentPrices.ts
> +    // FIXME we should probably have a polling rate so this expires?
thoughts on this? Maybe a SLOW polling rate is sufficient?

2024-12-20 00:19 UTC, PaulMcInnis commented on packages/berajs/src/actions/shared/getTokenCurrentPrices.ts
> +// import { gql } from "@apollo/client";
Need to figure out why this is such an issue, but sunk time into this one, it the apollo client wouldnt validate my chain argument here and refused to make the request so I've dont it manually to unblock the rest of this PR

2024-12-20 02:36 UTC, PaulMcInnis commented on apps/hub/src/app/pools/create/CreatePageContent.tsx
> +  const getStepVerification = (): {
I think the stepwise completion and a functional hook to verify the completion of each step make sense as another top-of-mind refactoring task

2024-12-20 02:39 UTC, PaulMcInnis commented on packages/berajs/src/hooks/modules/dex/useLiquidityMismatch.ts
> +    if (poolType === PoolType.ComposableStable) {
I want to cross-check here against what balancer does, since it's a bit tricky to give an actually accurate %'age loss estimate for the token inputs without some kind of arbitrage simulation. 

In the mean time, i've opted to just calculate the absolute difference between the provided liquidity and the median-weighted liquidity for that token, and if that difference goes above 100% we say that you could lose everything.

2024-12-23 16:12 UTC, PaulMcInnis commented on packages/berajs/src/hooks/modules/dex/useLiquidityMismatch.ts
> +    if (poolType === PoolType.ComposableStable) {
OK I fixed this problem. Confirmed as well that balancer does it this way (shortfalls and losses count)

2024-12-23 16:14 UTC, PaulMcInnis commented on packages/shared-ui/src/swap-fee.tsx
this was moved into the FE components as I needed PoolType

2024-12-23 16:15 UTC, PaulMcInnis commented on apps/hub/src/app/pools/components/ownership-input.tsx
this was renamed using git-mv

2024-12-23 19:25 UTC, bearpong requested changes
Please, clean it up a bit and review all copy and titles with the one on figma. I think they changed but no one told you. You can double check

2024-12-23 19:25 UTC, bearpong commented on apps/hub/src/app/pools/components/pool-creation-summary.tsx
> +    }
Please let's switch to enum, this index usage is a lil messy

2024-12-23 19:25 UTC, bearpong commented on apps/hub/src/app/pools/create/CreatePageContent.tsx
> +
Better move this into another file for readability

2024-12-23 19:25 UTC, bearpong commented on apps/hub/src/app/pools/create/CreatePageContent.tsx
> +  const getStepVerification = (): {
Let's move this into another file  pls

2024-12-23 19:25 UTC, bearpong commented on packages/berajs/src/actions/shared/getTokenCurrentPrices.ts
> +// import { gql } from "@apollo/client";
we can't have references to the chain name in the codebase, please use the variable. 

Can you pls share the error in dm? I'd like to help u, we can't merge the pr with hardcoded query

2024-12-23 19:25 UTC, bearpong commented on packages/berajs/src/hooks/tokens/useTokenCurrentPrices.ts
> +    // FIXME we should probably have a polling rate so this expires?
you might even use useSWRImmutable, whitelisting can only change with a governance proposal

2024-12-23 19:25 UTC, bearpong commented on packages/berajs/src/hooks/tokens/useTokenCurrentPrices.ts
> +    // FIXME we should probably have a polling rate so this expires?
for sure i wouldnt poll it on interval, and you might disable revalidateOnFocus too

2024-12-23 19:25 UTC, bearpong commented on packages/config/tailwind/index.ts
> +        semanticBlueSuccessBackground: "#121A1C",
we cannot have new ds styles in this PR. please use legacy styles

2024-12-23 20:22 UTC, PaulMcInnis commented on packages/config/tailwind/index.ts
> +        semanticBlueSuccessBackground: "#121A1C",
RE the polling, I think we probably need to since this is specifically price data we are fetching (I think maybe you confused this SWR with the one in the whitelisted BGT PR 👀 )

2024-12-23 22:00 UTC, PaulMcInnis commented on apps/hub/src/app/pools/create/CreatePageContent.tsx
> +
done!

2024-12-23 22:00 UTC, PaulMcInnis commented on apps/hub/src/app/pools/components/oracle-input.tsx
> +    /^0x[a-fA-F0-9]{40}$/.test(value);
done!

2024-12-23 22:01 UTC, PaulMcInnis commented on packages/config/tailwind/index.ts
> +        semanticBlueSuccessBackground: "#121A1C",
RE: ds styles, reverted back to green styling like in existing code 👍

2024-12-23 23:39 UTC, PaulMcInnis commented on apps/hub/src/app/pools/components/process-steps.tsx
> +              "relative flex w-fit md:w-full overflow-hidden rounded-sm border shadow-md ",
FYI what this will do is cause the window to change size while you type in longer pool symbols/names

2024-12-23 23:45 UTC, PaulMcInnis commented on apps/hub/src/app/pools/components/process-steps.tsx
> +            "relative w-full",
maybe worth running the w-full for smaller views by bobby/neph @bearpong ?

2024-12-24 09:34 UTC, Bearlinguer commented
Everything seems fine, but we still have the "Fee" in lower case. Just make it like "Fixed", "Custom" and "Governance" instead of all lower case.


<img width="379" alt="Screenshot 2024-12-24 alle 10 32 43" src="https://github.com/user-attachments/assets/fb0baddc-a75a-4915-8387-6c552f960341" />

2024-12-24 14:35 UTC, PaulMcInnis commented
> Everything seems fine, but we still have the "Fee" in lower case. Just make it like "Fixed", "Custom" and "Governance" instead of all lower case.
> 

👌 
![image](https://github.com/user-attachments/assets/9eacafe1-0542-4c95-9968-a9ca64bc299d)

2025-01-02 15:50 UTC, Bearlinguer requested changes
On Weighted pools:
The "Add Token" button is completely missing. 

<img width="1184" alt="Screenshot 2025-01-02 alle 16 46 48" src="https://github.com/user-attachments/assets/3851aa9b-0cf4-4f29-8844-e3d964f12f38" />

2025-01-03 13:58 UTC, bearpong approved these changes
still need minor changes but this can go in for now!

2025-01-03 13:58 UTC, merged

2025-01-03 14:44 UTC, Bearlinguer commented
If we're keeping only two tokens for the weighted, I've noticed something. If you start with a stable and put more than two tokens in, and then switch back to weighted, there's no error or warning.

Also some UI things:
- Components do not keep the same lengths, from one step to the other the dimensions change drastically. 

(Screen for ref.) 
1 the boxes arrive at half of the title "Create Pool"
2 the boxes cover all the space

![Screenshot 2025-01-03 alle 15 42 02](https://github.com/user-attachments/assets/e3905208-5113-46df-94d4-1c6de2cb0cc4)
![Screenshot 2025-01-03 alle 15 42 08](https://github.com/user-attachments/assets/16492f3f-40e7-4161-bb19-06b1f10ee270)