Bfe 331 vp support operator change and reward allocations
berachain/monobera pull request #248
Opened 2024-12-09 23:46 UTC by BrownBrownBear

2024-12-10 20:26 UTC, bearpong requested changes

2024-12-10 20:26 UTC, bearpong commented on packages/berajs/src/actions/pol/get-selected-validator.ts
> +}): Promise<GetSelectedValidatorQuery | undefined> => {
please let's make it clear that we're fetching validator by using the operator, so this should be `getValidatorByOperator`, also change the query names

2024-12-10 21:11 UTC, BrownBrownBear commented on packages/graphql/src/modules/pol/pol.graphql
> +  vaults(first: 1000, where: { isWhitelisted: true }) {
https://berachain-fe.atlassian.net/browse/BFE-407

2024-12-12 17:38 UTC, bearpong approved these changes

2024-12-12 17:39 UTC, merged