fix: governance UI fixes
berachain/monobera pull request #256
Opened 2024-12-12 14:40 UTC by thevolcanomanishere

2024-12-16 17:18 UTC, bearpong requested changes
I dropped some comments, generally I would avoid mixing huge refactors with bug fixing as it makes harder to review PRs.

Feel free to reach out for any questions

2024-12-16 17:18 UTC, bearpong commented on apps/hub/src/app/governance/[genre]/components/proposals-list.tsx
> +  useProposalStatusMonitor(data?.flat().length ? data.flat() : []);
This is useless on ProposalList since ProposalCard does not use queryKey `["usePollProposal", proposal.id]`, that's only use on ProposalDetail. 

Said that, I think you might wanna remove the useProposalStatusMonitor and move the logic in `usePollProposal` and `usePollAllProposals`. In this way the timeout/interval is embedded in the functions we already use

2024-12-16 17:18 UTC, bearpong commented on packages/berajs/src/hooks/modules/governance/usePollAllProposals.ts
> +    hasMore: (data.at(-1)?.length ?? 0) === (args.perPage ?? DEFAULT_PER_PAGE),
why these two changes? Just makes code harder to read imo

2024-12-16 17:18 UTC, bearpong commented on packages/berajs/src/hooks/modules/governance/usePollAllProposals.ts
> +    hasMore: (data.at(-1)?.length ?? 0) === (args.perPage ?? DEFAULT_PER_PAGE),
but i see that we have no defined guidelines

2024-12-17 16:19 UTC, thevolcanomanishere commented
![Screenshot 2024-12-17 at 16 18 48](https://github.com/user-attachments/assets/c9798623-a4f0-475d-a207-023fc253d0d1)
![Screenshot 2024-12-17 at 16 19 05](https://github.com/user-attachments/assets/e3cb87d3-6b98-4483-a537-fc85a945929c)

2024-12-17 17:38 UTC, bearpong requested changes
Please can you also add the timelock to computeActualStatus? Right now after queueing a proposal, the FE shows the proposal as pending execution, i think that might be related to that

2024-12-17 17:38 UTC, bearpong commented on apps/hub/src/app/governance/[genre]/proposal/[proposalId]/components/proposal-timeline.tsx
> +  const initialVotingStep: StepProps = {
Please revert this refactor, just keep the updates on the labels (e.g. Queue endung etc...) and the succededAt feature. I still see issues but there was no need to change all the logic here and at the end of the day this might not be worth it as a refactoring.

2024-12-19 09:14 UTC, bearpong requested changes
I made a small commit to fix a small bug and add the remaining time when proposal is in queue.

Plese can you address the comment on the queue threshold? 

Moreover, I got a reading .status of undefined on a proposal when changing from pending timeout expired. This got the proposal stuck as pending till I refreshed the page. Can you check please?

Thank you!

2024-12-23 16:23 UTC, bearpong approved these changes
LGTM

2024-12-23 16:23 UTC, merged