feat(berajs): add gas limit estimation to prevent hitting gas limits …
berachain/monobera pull request #258
Opened 2024-12-12 19:53 UTC by BrownBrownBear

…set by validator nodes

2024-12-16 10:42 UTC, bearpong requested changes
Please after addressing the comments, might you also add the nonce to the tx in this PR? So that we can test all changes to useBeraContractWrite at once.

It'd also be useful to check if useCreatePool works without the gasLimit hardcoded

2024-12-16 10:42 UTC, bearpong commented on packages/berajs/src/hooks/useContractWrite/useBeraContractWrite.ts
> +              increaseByPercentage(wagmiPubEstimateContractGas, 10) ?? gasLimit,
Here I think we should:
1. remove default gasLimit value
2. don't fetch estimateContractGas unless gasLimit is unset
3. use Promise.allSettled and:
- throw error if simulateContract reverts
- use  DEFAULT_METAMASK_GAS_LIMIT if no gasLimit was provided and estimateContractGas failed

`increaseByPercentage` should be removed since we realized that gas is different from the gas cost. Attaching here a screenshot that confirms our hints 
<img width="654" alt="Screenshot 2024-12-16 at 11 40 41" src="https://github.com/user-attachments/assets/3406aa70-a38e-4071-afc6-9840043420f6" />

2024-12-16 10:42 UTC, bearpong commented on packages/berajs/src/utils/const.ts
> +export const DEFAULT_METAMASK_GAS_LIMIT = 7920027n; // NOTE: this is the metamask gas limit, https://github.com/MetaMask/metamask-extension/blob/06cf7459b963e26d0ae60312d4f9a342d07ab89d/ui/pages/conf
can we use JSdocs for this?

2024-12-19 16:02 UTC, BrownBrownBear commented on packages/berajs/src/hooks/useContractWrite/useBeraContractWrite.ts
> +              increaseByPercentage(wagmiPubEstimateContractGas, 10) ?? gasLimit,
<img width="1457" alt="Screenshot 2024-12-19 at 11 01 51 AM" src="https://github.com/user-attachments/assets/8b866a47-31d9-4f32-9b15-dd46b676e609" />
For example, if I didn't bump this, you can see it's greater than 90% and the txn would not have gone through.

2024-12-19 16:04 UTC, BrownBrownBear commented
<img width="1377" alt="Screenshot 2024-12-19 at 11 04 16 AM" src="https://github.com/user-attachments/assets/458fbe5b-6f33-4331-890e-0965546e34d9" />
I did attach my concerns with adding out own nonce but things work. And if people are trying to queue many txns, we can still calculate the pending txns!

2024-12-19 16:35 UTC, BrownBrownBear commented
> Please after addressing the comments, might you also add the nonce to the tx in this PR? So that we can test all changes to useBeraContractWrite at once.
> 
> It'd also be useful to check if useCreatePool works without the gasLimit hardcoded

I did check and simulate if useCreatePool does work. I just didn't create a pool since it can throw off the prices we have on boonet we have right now

2024-12-19 17:41 UTC, bearpong approved these changes
LGTM

2024-12-23 17:37 UTC, bearpong approved these changes

2024-12-23 17:38 UTC, merged