feat(hub): update loading times of tokens for swaps and pools
berachain/monobera pull request #266
Opened 2024-12-16 22:46 UTC by BrownBrownBear

This is what we were talking about on friday with a new avatar component that could load base64 items. Tokens with a base64 parameter should load instantly and our token list should be loaded faster on the swaps page. 

I can make the time to load remote tokens quicker that are PNGs or other formats since we are sending in the list via the server page by removing a loading prop in the component. HOWEVER, if images have incorrect URLs or there's not a good internet connection, this can cause a broken image to show up and we won't be able to show a fallback. Server Components in Next.js run entirely on the server and are not tied to browser-side lifecycle events like onLoad or onError. Such callbacks are inherently client-side concepts because they rely on events occurring in the browser.

I thought this was a happy medium. I can also see us running into an issue in the future of this default list getting too big. 
The performance impact of string serialization can be problematic and we're sending a huge list down from a server component to a clientside component. 

We can always try
- Reducing the size of the token list file so we get base64 data only.
- Loading the token list data dynamically on the client side like we're currrently doing

2024-12-17 14:32 UTC, bearpong requested changes

2024-12-19 16:39 UTC, BrownBrownBear commented on .scripts/vercel-local-install.sh
> +fi
Sorry, this was for development and continued over. Deleted now

2024-12-19 16:40 UTC, BrownBrownBear commented on .scripts/set-local-install.js
> +}
Yeah, it was just so that I could run it with pnpm for development. I deleted it now

2024-12-19 17:12 UTC, BrownBrownBear commented on packages/ui/src/custom-avatar.tsx
> +          `h-[${height}px] w-[${width}px]`,
I've removed this and let the sizing prop decide the size with tailwind like we had with the original shadcn avatar

2024-12-19 17:12 UTC, BrownBrownBear commented on packages/shared-ui/src/token-icon.tsx
> +        return `data:image/svg+xml;base64,${uploadedToken.base64}`;
Defaulted to already be in the JSON or will assume that it's SVG after.

2024-12-19 17:27 UTC, BrownBrownBear commented on apps/hub/src/app/layout.tsx
> +  const fetchedTokenList = JSON.parse(fileContent);
You're right. I added a check to fetch data from an external site too.

2024-12-19 19:53 UTC, BrownBrownBear commented on packages/berajs/src/hooks/useTokens.ts
> +      revalidateOnMount: true,
I moved it outside the swr hook. I remove the revalidate on mount because we don't need to refetch localstorage anymore as it's latest state is maintained by the useLocalStorage hook and we have its data as a dependency in a useMemo of combined data.

2024-12-23 17:03 UTC, bearpong approved these changes

2024-12-23 17:47 UTC, merged