Display Vault APY in pools table
berachain/monobera pull request #282
Opened 2024-12-24 19:04 UTC by PaulMcInnis

Like it says on the box, now we have a sortable APY column in pools:

Note:

- I think when we have many pools this might become a scalability issue (pulling vaults for every pool vs using pagination), so i’ve filed a tech debt [issue](https://berachain-fe.atlassian.net/browse/BFE-444?atlOrigin=eyJpIjoiMmZkNGRlYzUyOTBiNGNmNWI5NjVjMDViNmI3NzI3MWEiLCJwIjoiaiJ9) for this. 
- Thinking maybe we wanna title the column in a way that its clear that this is vault APY? (Does this matter?)
- Some pools dont currently have vaults, so I’m displaying a - character for those
- Some APYs are pretty high on testnet rn, need to berify that this is testnet tokenomics and not an issue elsewhere. (If the pool has low liquidity should we show APY at all?)

2025-01-02 11:38 UTC, bearpong requested changes
Please, instead of adding a column here, APR should be the sum of all pool APR + bgt APY.

![image](https://github.com/user-attachments/assets/fc9741f6-f2e3-4803-9bf7-327f7899be54)

Moreover, please remove bgt capture and show BGT APY instead in this component.

![image](https://github.com/user-attachments/assets/5884eb7b-1e69-46ac-8432-89d22e51aa81)

2025-01-02 11:38 UTC, bearpong commented on apps/hub/src/app/pools/usePoolTable.tsx
> +      },
APY is returned already as percentage from the BE, that's the reason why numbers are insanely high.

If you want to use percentage, you have to set value as apy / 100. Moreover if APY is negative (-1) it means it's actually null.

2025-01-02 11:38 UTC, bearpong commented on apps/hub/src/app/pools/usePoolTable.tsx
> +      },
I think this column should not exists anyway, but comment is useful in other cases.

2025-01-02 19:32 UTC, PaulMcInnis commented on apps/hub/src/app/pools/usePoolTable.tsx
> +      },
gotcha! nuking the column but remembering this.

2025-01-06 20:03 UTC, bearpong requested changes
Can you check why sometimes at first render it says it's not whitelisted?

<img width="1472" alt="image" src="https://github.com/user-attachments/assets/032a0ad7-a9dd-42b1-83db-10b11311bb60" />


APR should be a percentage, let's call it `Pool APY`

<img width="263" alt="Screenshot 2025-01-06 at 14 59 12" src="https://github.com/user-attachments/assets/d317480b-f3e5-4019-9579-878861f5296a" />

Also on the right, when not connected/not provided liquidity we should show `Earn APY <total APY % in green>` as on the Figma, moreover the vault info should be shown anyway.

<img width="1607" alt="Screenshot 2025-01-06 at 15 00 48" src="https://github.com/user-attachments/assets/cfff7fa5-85e6-48b2-84ae-e0bbcc7f7c5b" />

2025-01-07 00:43 UTC, PaulMcInnis commented on apps/hub/src/app/pools/usePoolTable.tsx
> +            row.original.userBalance?.walletBalance !== "0";
done!

2025-01-07 01:16 UTC, PaulMcInnis commented
OK now I've also fixed:

1. vault whitelisted & create now are only shown when the page is fully loaded
2. Pool APY is displayed as a numeric value 
3. we always show the vault if one exists
4. we show the combined (effective) APY as a part of the deposit copy

Open Q: maybe we could instead display the combined APR everywhere?

2025-01-07 17:25 UTC, bearpong approved these changes

2025-01-07 17:25 UTC, merged