Bfe 35 berps delete the markets page to replace a markets dropdown
berachain/monobera pull request #33
Opened 2024-08-22 16:12 UTC by bearpong

Removes `/markets` page and restyles create position component

2024-08-28 14:21 UTC, BrownBrownBear commented
1. From a design perspective, can we move the markets table from the old markets page to the home page? I think it has some important information and can go right below the markets infinite scroll tiles. 
2. Can we add open interest in both long and short to the new markets drop down? It doesn't have to be green/red and can be just a flat white.
3. This doesn't have to be added now, but we'll need to eventually put a max height on the dropdown and add a scroll when we have more markets. Just something to be wary about. 
4. I've added a screen recording here. I feel like if we're minimizing the TP/SL/Leverage, we should always have the defaults set in place when we switch the type of order (Long/Short,Market/Limit). This provides a cleaner UX as the user doesn't need to open the advanced details and their order will go through with "expected configuration".

https://github.com/user-attachments/assets/4979beff-90bc-4478-a949-5f1a5f860089

2024-08-28 16:15 UTC, BrownBrownBear requested changes
Code looks good to me. JUst need those changes from my previous comment

2024-08-30 16:25 UTC, BrownBrownBear commented
> Sorry, I had forgot about the open interest updates, done now. About the market table in the homepage, I agree there's some useful information but it'd be very similiar to the data in the markets infinite scroll tiles, I'd avoid repetitions. Maybe should we consider it for the homepage redesign bobby's working onto?

Sounds good. We can keep it as is and don't worry about adding that table. we can look back into it when we decide to go live with mainnet for perps. 

Three last quick changes for perps:
- `Open Interest` header to `Open Interest (L/S)`
- Add 24H trades for each market to market details popover
- Fix padding on dropdown when in smaller screens

2024-08-30 16:28 UTC, BrownBrownBear commented
Found a bug when switching between long and short, the long buttons remain grayed out:

https://github.com/user-attachments/assets/6c96ec01-1753-45d9-8d1e-0501b61b853d

2024-08-30 16:30 UTC, BrownBrownBear commented on apps/perp/src/app/berpetuals/components/instrument-dropdown.tsx
> +        className={`my-1 w-full p-0 max-lg:min-w-[calc(100vw-1rem)] lg:mx-2 ${DYNAMIC_DROPDOWN_MOBILE_HEIGHTS[activeBanners]} ${DYNAMIC_DROPDOWN_DESKTOP_HEIGHTS[activeBanners]}`}
Here's the padding issue where the left side is padding is not aligned with the right side
<img width="755" alt="Screenshot 2024-08-30 at 12 24 18 PM" src="https://github.com/user-attachments/assets/a7e9674d-f112-4ab8-8b39-f0b7f05bfb97">

2024-08-30 16:46 UTC, BrownBrownBear commented
Another weird interaction. I understand what's happening but was wondering if we could make the UX better. The max SL is 300% and that's what it's currently is but the SL button that's highlight is the grayed out 900%. Not sure what the best way to resolve this is but maybe we can unhighlight 900% when it's not available and if the TP/SL price lines up with the percentage options we give the user (50, 100, 300, 900), they'll be highlighted? 


https://github.com/user-attachments/assets/ef45bd3e-8089-461e-80ab-c8ca9ad3ac99

2024-08-30 16:50 UTC, BrownBrownBear requested changes

2024-08-30 16:50 UTC, BrownBrownBear commented on apps/perp/src/app/berpetuals/components/instrument-dropdown.tsx
> +    header: "Open Interest",
Can you change this to: `Open Interest (L/S)`

2024-08-30 16:50 UTC, BrownBrownBear commented on apps/perp/src/app/berpetuals/components/tpsl.tsx
> +                        }${tpPercentBN.toString(10)}%)`
Can we try and clean this percentage up when it's an invalid profit (i.e. placing a long order and we set a take profit lower than the mark price of the market)
<img width="372" alt="Screenshot 2024-08-30 at 12 39 29 PM" src="https://github.com/user-attachments/assets/2231baa1-493a-4acc-8747-fc1272d082d4">
<img width="419" alt="Screenshot 2024-08-30 at 12 39 32 PM" src="https://github.com/user-attachments/assets/f532000b-724b-420a-a337-d03f00f93071">

2024-08-30 16:50 UTC, BrownBrownBear commented on apps/perp/src/app/berpetuals/components/tpsl.tsx
> +                        }${tpPercentBN.toString(10)}%)`
I've added the before and after

2024-08-30 16:50 UTC, BrownBrownBear commented on packages/shared-ui/src/approve-button.tsx
> -  useEffect(() => {
Good use of removing calculating client width here!

2024-08-30 16:50 UTC, BrownBrownBear commented on packages/berajs/src/hooks/useTpsl.ts
> +        "0.00000001",
Why is this 0.00000001?

2024-08-30 16:55 UTC, bearpong commented
Yup, i noticed that, however i think this is the best way so far and gns behaves in the same way. If user clicks on 900%, i don't think it'd be good UX pattern if we unselected 900% as the leverage goes down, even for a second. what do you say?

2024-08-30 18:19 UTC, bearpong commented on packages/berajs/src/hooks/useTpsl.ts
> +        "0.00000001",
nvm i'm setting it to 0

2024-08-30 18:38 UTC, bearpong commented on packages/shared-ui/src/approve-button.tsx
> -  useEffect(() => {
thank youu

2024-08-30 18:47 UTC, bearpong commented on apps/perp/src/app/berpetuals/components/tpsl.tsx
> +                        }${tpPercentBN.toString(10)}%)`
ty, fixed

2024-09-04 13:32 UTC, merged